name: Build and Test
on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
      - cron:  '0 7 * * *'
  repository_dispatch:
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout azure-javaee-iaas
        uses: actions/checkout@v2
        with:
          repository: Azure/azure-javaee-iaas
          path: azure-javaee-iaas        
      - name: Checkout arm-ttk
        uses: actions/checkout@v2
        with:
          repository: Azure/arm-ttk
          path: arm-ttk     
      - name: Checkout arm-oraclelinux-wls-cluster
        uses: actions/checkout@v2
        with:
          path: arm-oraclelinux-wls-cluster  
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build azure-javaee-iaas
        run: mvn -DskipTests clean install --file azure-javaee-iaas/pom.xml
      - name: Build and test arm-oraclelinux-wls-cluster
        run: mvn -Ptemplate-validation-tests clean install --file arm-oraclelinux-wls-cluster/pom.xml

      - name: Build and test addnode
        run: mvn -Ptemplate-validation-tests clean install --file addnode/pom.xml

      - name: Get version information from arm-oraclelinux-wls-cluster/pom.xml
        id: version
        run: echo "##[set-env name=version;]$(awk '/<version>[^<]+<\/version>/{gsub(/<version>|<\/version>/,"",$1);print $1;exit;}' arm-oraclelinux-wls-cluster/arm-oraclelinux-wls-cluster/pom.xml)"
      - name: Print version
        run: echo $version 
      - name: Generate artifact name         
        run: echo "##[set-env name=artifactName;]arm-oraclelinux-wls-cluster-$version-arm-assembly"  
      - name: Print artifact name
        run: echo $artifactName
      - name: Output artifact name
        id: artifact_file
        run: echo "##[set-output name=artifactName;]arm-oraclelinux-wls-cluster-$version-arm-assembly"
      - name: Generate zip package path
        id: artifact_path
        run: echo "##[set-output name=artifactPath;]arm-oraclelinux-wls-cluster/arm-oraclelinux-wls-cluster/target/$artifactName"
      - name: Output artifact path
        run: echo $artifactPath
        env: 
          artifactPath: ${{steps.artifact_path.outputs.artifactPath}}
      - name: Unzip the package as upload action will zip again 
        run: unzip arm-oraclelinux-wls-cluster/arm-oraclelinux-wls-cluster/target/$artifactName.zip -d arm-oraclelinux-wls-cluster/arm-oraclelinux-wls-cluster/target/$artifactName

      - name: Archive arm-oraclelinux-wls-cluster template
        uses: actions/upload-artifact@v1 
        if: success()
        with:
          name: ${{steps.artifact_file.outputs.artifactName}}
          path: ${{steps.artifact_path.outputs.artifactPath}}

      - name: Get version information from addnode/pom.xml
        id: addnode_version
        run: echo "##[set-env name=addnode_version;]$(awk '/<version>[^<]+<\/version>/{gsub(/<version>|<\/version>/,"",$1);print $1;exit;}' arm-oraclelinux-wls-cluster/addnode/pom.xml)"
      - name: Print addnode template version
        run: echo $addnode_version 
      - name: Generate addnode template artifact name         
        run: echo "##[set-env name=addnode_artifactName;]arm-oraclelinux-wls-cluster-addnode-$addnode_version-arm-assembly"  
      - name: Print addnode template artifact name
        run: echo $addnode_artifactName
      - name: Output addnode template artifact name
        id: addnode_artifact_file
        run: echo "##[set-output name=addnode_artifactName;]arm-oraclelinux-wls-cluster-addnode-$addnode_version-arm-assembly"
      - name: Generate addnode template zip package path
        id: addnode_artifact_path
        run: echo "##[set-output name=addnode_artifactPath;]arm-oraclelinux-wls-cluster/addnode/target/$addnode_artifactName"
      - name: Output addnode template artifact path
        run: echo $addnode_artifactPath
        env: 
          addnode_artifactPath: ${{steps.addnode_artifact_path.outputs.addnode_artifactPath}}
      - name: Unzip the package as upload action will zip again 
        run: unzip arm-oraclelinux-wls-cluster/addnode/target/$addnode_artifactName.zip -d arm-oraclelinux-wls-cluster/addnode/target/$addnode_artifactName

      - name: Archive arm-oraclelinux-wls-cluster addnode template
        uses: actions/upload-artifact@v1 
        if: success()
        with:
          name: ${{steps.addnode_artifact_file.outputs.addnode_artifactName}}
          path: ${{steps.addnode_artifact_path.outputs.addnode_artifactPath}}
